---
small_host:
  cpu: 400 
  memory: 8G
  disk: 16G
  #iops: 2000
  traits: []

large_host:
  cpu: 800
  memory: 32G
  disk: 32g
  #iops: 4000

huge_host:
  cpu: 1600
  memory: 48G
  disk: 100g
  #iops: 4000
